export const API_ENDPOINTS = {
  auth: {
    login: '/api/v1/auth/login',
    register: '/api/v1/auth/register',
    forgotPassword: '/api/v1/auth/forgot-password',
    resetPassword: '/api/v1/auth/reset-password',
    refreshToken: '/api/v1/auth/refresh-token',
    logout: '/api/v1/auth/logout',
    changePassword: '/api/v1/auth/change-password',
    me: '/api/v1/auth/me',
    reactivateAccount: '/api/v1/auth/reactivate-account',
  },
  courses: {
    publicList: '/api/v1/courses/public',
    publicCategories: '/api/v1/courses/public/categories',
    publicLevels: '/api/v1/courses/public/levels',
    publicDetail: (courseId: string) => `/api/v1/courses/public/${courseId}`,
    authorizedDetail: (courseId: string) => `/api/v1/courses/${courseId}`,
    listForAdmin: '/api/v1/courses',
    myCourses: '/api/v1/courses/me',
    create: '/api/v1/courses',
    update: (courseId: string) => `/api/v1/courses/${courseId}`,
    remove: (courseId: string) => `/api/v1/courses/${courseId}`,
    publish: (courseId: string) => `/api/v1/courses/${courseId}/publish`,
    unpublish: (courseId: string) => `/api/v1/courses/${courseId}/unpublish`,
    image: {
      public: (courseId: string) => `/api/v1/courses/public/${courseId}/image`,
      secured: (courseId: string) => `/api/v1/courses/${courseId}/image`,
    },
    lessons: {
      create: (courseId: string) => `/api/v1/courses/${courseId}/lessons`,
      update: (courseId: string, lessonId: string) => `/api/v1/courses/${courseId}/lessons/${lessonId}`,
      remove: (courseId: string, lessonId: string) => `/api/v1/courses/${courseId}/lessons/${lessonId}`,
      video: (courseId: string, lessonId: string) => `/api/v1/courses/${courseId}/lessons/${lessonId}/video`,
      playbackUrl: (courseId: string, lessonId: string) => `/api/v1/courses/${courseId}/lessons/${lessonId}/video/playback-url`,
    },
  },
  enrollments: {
    create: '/api/v1/enrollments',
    me: '/api/v1/enrollments/me',
    byId: (enrollmentId: number | string) => `/api/v1/enrollments/${enrollmentId}`,
    byCourse: (courseId: string) => `/api/v1/enrollments/by-course/${courseId}`,
  },
  payments: {
    create: '/api/v1/payments',
    me: '/api/v1/payments/me',
    invoice: (paymentId: string) => `/api/v1/payments/${paymentId}/invoice`,
  },
  users: {
    me: '/api/v1/users/me',
    avatar: '/api/v1/users/me/avatar',
  },
  instructor: {
    me: '/api/v1/instructors/me',
    apply: '/api/v1/instructors/me/apply',
    updateMe: '/api/v1/instructors/me',
  },
  reviews: {
    base: '/api/v1/reviews',
    byCourse: (courseId: string) => `/api/v1/reviews/courses/${courseId}`,
    byCourseSummary: (courseId: string) => `/api/v1/reviews/courses/${courseId}/summary`,
    myReviews: '/api/v1/reviews/me',
    byId: (reviewId: string) => `/api/v1/reviews/${reviewId}`,
  },
} as const
